### ISSUE TITLE
unifying repository

### ISSUE THREAD

**Issue by Helias** [Tony931023/mod-bg-slaveryvalley#2]
on AzerothCore we have this repository as reference https://github.com/azerothcore/mod-bg-slaveryvalley/
and here on gitlab https://gitlab.com/Helias/mod-bg-slaveryvalley the repository with all the content, client and server

would be great to use only one repository for any improvements or support

I ask you to make Merge Request / Pull Request on https://gitlab.com/Helias/mod-bg-slaveryvalley if you want to improve this

**Comment by Helias** [comment]
@Tony931023

**Comment by Tony931023** [comment]
yes @helias I found this source via google some time ago, and I was trying some things, then I found the source at https://gitlab.com/Helias/mod-bg-slaveryvalley which is the one that works in the latest versions of AC , then I do a PR with the update of the maps, vmaps... for the latest update of AC.
In this one I only tried to change the BG loading photo and try to lower the level required to enter the BG to lvl 70 since you have to have lvl 71 to use it but I couldn't find where to change it, where I wanted to implement it on my private server www.amanthul.nat.cu, is a progressive something similar to CC, where it even copies its own rules, where I am testing and sharing errors found with AC, always seeking to keep the AC source as stable as possible

![WoWScrnShot_061422_065306](https://user-images.githubusercontent.com/4868094/176488280-d5a9c508-185b-4399-a757-84ef534b718a.jpg)

**Comment by Helias** [comment]
`then I do a PR with the update of the maps, vmaps... for the latest update of AC.`
I didn't see any PR, please do it if you can, moreover usually we release the DBCs file in enUS, but would be great to release them in multiple languages, so if you can add esES/esMX next to enUS would be great!

P.S. I made this https://github.com/Tony931023/mod-bg-slaveryvalley/pull/3
